backend:
  name: "git-gateway"
  branch: "master"
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "rss"
    label: "RSS"
    folder: "src/data/rss"
    create: true
    slug: "{{feed}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-post" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Feed", name: "feed", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "rssFeed"
    label: "RSS Feed"
    folder: "src/data/rss/configs"
    create: true
    slug: "{{feedKey}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-feed" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feed Key", name: "feedKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }

  - name: "fb"
    label: "Facebook"
    folder: "src/data/fb"
    create: true
    slug: "{{page}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-post" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Page", name: "page", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }

  - name: "fbPage"
    label: "Facebook Page"
    folder: "src/data/fb/configs"
    create: true
    slug: "{{pageKey}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Key", name: "pageKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }

  - name: "ird"
    label: "IRD Resource"
    folder: "src/data/ird"
    create: true
    slug: "ird-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "ird-resource" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
  
  - name: "deadline"
    label: "Deadline"
    folder: "src/data/deadlines"
    create: true
    slug: "{{slug}}-{{date}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "deadline" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Organization", name: "org", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
