backend:
  name: "git-gateway"
  branch: "master"
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "rss"
    label: "RSS"
    folder: "src/data/rss"
    create: true
    slug: "{{source}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-post" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "rssSource"
    label: "RSS Source"
    folder: "src/data/rss/sources"
    create: true
    slug: "{{slug}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-source" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Source Key", name: "sourceKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }

  - name: "fb"
    label: "Facebook"
    folder: "src/data/fb"
    create: true
    slug: "{{source}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-post" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Page", name: "page", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }

  - name: "fbSource"
    label: "Facebook Source"
    folder: "src/data/fb/sources"
    create: true
    slug: "{{slug}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-source" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Source Key", name: "sourceKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }

  - name: "ird"
    label: "IRD Resource"
    folder: "src/data/ird"
    create: true
    slug: "{{source}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "ird-resource" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Source", name: "source", widget: "list" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
