backend:
  name: 'git-gateway'
  branch: 'master'
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'rss'
    label: 'RSS'
    folder: 'src/data/rss'
    create: true
    slug: '{{source}}-{{year}}-{{month}}-{{day}}'
    extension: json
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'rss-post' }
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'datetime' }

  - name: 'facebook'
    label: 'FB'
    folder: 'src/data/fb'
    create: true
    slug: '{{source}}-{{year}}-{{month}}-{{datetime}}'
    extension: json
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'fb-post' }
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Title', name: 'name', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Date', name: 'start_time', widget:'text' }
      - { label: 'Location', name: 'location', widget: 'string' }
